language: minimal

services:
  - docker

install:
  - docker build -t vue .

script:
  - |
    docker run --rm -it \
      -v "$(pwd)":/src \
      -v /var/run/docker.sock:/var/run/docker.sock \
    iorubs/dgoss run vue sleep 1d

deploy:
  provider: script
  script:
    - curl -X POST https://cloud.docker.com/api/build/v1/source/76b71e53-18c2-4c18-bc1a-0cfdceaf5fb4/trigger/dff74c74-aa36-4353-b964-a80e52d172fb/call/
  skip_cleanup: true
  on:
    branch: master

