language: minimal

services:
  - docker

install:
  - docker build -t vue .

script:
  - |
    docker run --rm -it \
      -v "$(pwd)":/src \
      -v /var/run/docker.sock:/var/run/docker.sock \
    iorubs/dgoss run vue sleep 1d

deploy:
  provider: script
  script:
    - curl -X POST https://cloud.docker.com/api/build/v1/source/${SOURCE_ID}/trigger/${TRIGGER_ID}/call/
  skip_cleanup: true
  on:
    branch: master

