language: minimal

services:
  - docker

install:
  - docker build -t vue .

script:
  - |
    docker run --rm -it \
      -v "$(pwd)":/src \
      -v /var/run/docker.sock:/var/run/docker.sock \
    iorubs/dgoss run vue sleep 1d
